name: campusconnect
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0

  # State Management
  flutter_riverpod: ^2.4.9
  equatable: ^2.0.5

  # Navigation
  go_router: ^13.1.0

  # Backend
  supabase_flutter: ^2.12.0
  http: ^1.2.1

  # Utilities
  permission_handler: ^11.1.0
  url_launcher: ^6.2.2
  file_picker: ^8.0.3
  intl: ^0.20.0
  table_calendar: ^3.1.1
  shared_preferences: ^2.3.2
  
  # Export & PDF
  pdf: ^3.10.0
  printing: ^5.11.0
  path_provider: ^2.1.0
  emoji_picker_flutter: ^4.4.0
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo/app_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/logo/

