name: campusconnect
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0

  # State Management
  flutter_riverpod: ^2.4.9
  equatable: ^2.0.5

  # Navigation
  go_router: ^13.1.0

  # Backend
  supabase_flutter: ^2.3.0
  http: ^1.2.1

  # Utilities
  permission_handler: ^11.1.0
  url_launcher: ^6.2.2
  file_picker: ^8.0.3
  intl: ^0.19.0
  table_calendar: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
